### ISSUE TITLE
calculation is  too long more than 12 hours and still running 

### ISSUE THREAD

**Issue by Sandy4321** [alexeygrigorev/classifying-crisis-reports-dsc#2]
how long calculation should be?
I use lap top with 16 GB RAM , simulate during 12 hours and still running
it uses 10 GB RAM
how it should be, how long , what output looks like? , 
if I am doing something wrong?
Spasibo
Sander
may we communicate by email?
it is what I see on screen for 12 hours

  0%|          | 0/30 [00:00<?, ?it/s]
  3%|3         | 1/30 [00:02<01:13,  2.54s/it]
  7%|6         | 2/30 [00:05<01:14,  2.68s/it]
 10%|#         | 3/30 [00:09<01:18,  2.92s/it]
 13%|#3        | 4/30 [00:12<01:21,  3.13s/it]
 17%|#6        | 5/30 [00:16<01:22,  3.30s/it]
 20%|##        | 6/30 [00:19<01:21,  3.40s/it]
 23%|##3       | 7/30 [00:23<01:21,  3.53s/it]
 27%|##6       | 8/30 [00:27<01:19,  3.60s/it]
 30%|###       | 9/30 [00:31<01:19,  3.79s/it]
 33%|###3      | 10/30 [00:35<01:17,  3.86s/it]
 37%|###6      | 11/30 [00:40<01:15,  3.99s/it]
 40%|####      | 12/30 [00:44<01:13,  4.06s/it]
 43%|####3     | 13/30 [00:48<01:10,  4.13s/it]
 47%|####6     | 14/30 [00:53<01:07,  4.22s/it]
 50%|#####     | 15/30 [00:58<01:07,  4.53s/it]
 53%|#####3    | 16/30 [01:03<01:06,  4.73s/it]
 57%|#####6    | 17/30 [01:09<01:05,  5.01s/it]
 60%|######    | 18/30 [01:14<01:02,  5.20s/it]
 63%|######3   | 19/30 [01:20<00:59,  5.38s/it]
 67%|######6   | 20/30 [01:24<00:49,  4.96s/it]
 70%|#######   | 21/30 [01:28<00:42,  4.75s/it]
 73%|#######3  | 22/30 [01:34<00:39,  4.89s/it]
 77%|#######6  | 23/30 [01:39<00:35,  5.02s/it]
 80%|########  | 24/30 [01:44<00:30,  5.15s/it]
 83%|########3 | 25/30 [01:50<00:26,  5.24s/it]
 87%|########6 | 26/30 [01:55<00:21,  5.27s/it]
 90%|######### | 27/30 [02:00<00:15,  5.21s/it]
 93%|#########3| 28/30 [02:06<00:10,  5.29s/it]
 97%|#########6| 29/30 [02:11<00:05,  5.39s/it]
100%|##########| 30/30 [02:17<00:00,  5.35s/it]

**Comment by alexeygrigorev** [comment]
On my machine it takes a few hours. You probably need around 32 gb of RAM for that
